name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kondinski-survey"
          heroku_email: "kondinskis@gmail.com"
          usedocker: true
          docker_build_args: |
            API_BASE_URL
        env:
          API_BASE_URL: ${{secrets.API_BASE_URL}}
